# tensorflow 이미지를 베이스로 저번 과제 파일 합쳐서 이미지 만들기
FROM tensorflow/tensorflow:latest
LABEL maintainer "jjaegii <hn06038@gmail.com>"
RUN apt-get update && apt-get install python3 python3-pip -y
WORKDIR /src
COPY requirements.txt .
COPY module/cnn_model.py module/cnn_model.py
COPY train.py .
RUN pip3 install -r requirements.txt

# 이미지 빌드 후
# docker run -it -v ./train:/src/train -v ./test:/src/test -v ./model:/src/model 이미지이름:태그
ENTRYPOINT [ "python3" ]
CMD [ "train.py" ]