# tensorflow 이미지를 베이스로 저번 과제 파일 합쳐서 이미지 만들기
FROM tensorflow/tensorflow:latest
LABEL maintainer "jjaegii <hn06038@gmail.com>"
WORKDIR /src
COPY templates templates/
COPY inference.py .
RUN pip3 install flask pillow
ENV MODEL_PATH /src/model/mnist.h5

# 이미지 빌드 후
# docker run -it -v ./model:/src/model -p 5000:5000 이미지이름:태그
ENTRYPOINT [ "python3" ]
CMD [ "inference.py" ]